// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var areYouCrushingIt = /* Yes */0;

var pet = /* Dog */0;

var pet2 = /* Dog */0;

var myAccount = {
  TAG: /* Facebook */1,
  _0: "Josh",
  _1: 26
};

var friendAccount = {
  TAG: /* Instagram */0,
  _0: "Jenny"
};

var me = {
  TAG: /* Id */1,
  name: "Joe",
  password: "123"
};

var meTwo = {
  TAG: /* Id */1,
  _0: {
    name: "Ivy",
    password: "qwer"
  }
};

exports.areYouCrushingIt = areYouCrushingIt;
exports.pet = pet;
exports.pet2 = pet2;
exports.myAccount = myAccount;
exports.friendAccount = friendAccount;
exports.me = me;
exports.meTwo = meTwo;
/* No side effect */
