// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function render(color) {
  console.log("...");
  
}

console.log("Other color than red and blue: ", "Papayawhip");

console.log("Other color than red and blue: ", "Papayawhip");

var colors = ["Red"];

var myColor = "Red";

var admin = "admin";

var one = "1";

var oneA = "1a";

var acc = {
  NAME: "Instargram",
  VAL: "Test"
};

var c = "Ruby";

var content = {
  NAME: "Paragraph",
  VAL: {
    NAME: "Text",
    VAL: "Hello World"
  }
};

var basic = "Red";

var foreground = "Green";

var background = "Red";

var color = "Red";

var capitalized = "#Hello";

var lowercased = "#goodbye";

var err = {
  NAME: "error",
  VAL: "oops!"
};

var num = "1";

exports.myColor = myColor;
exports.render = render;
exports.admin = admin;
exports.one = one;
exports.oneA = oneA;
exports.acc = acc;
exports.c = c;
exports.content = content;
exports.basic = basic;
exports.foreground = foreground;
exports.background = background;
exports.color = color;
exports.colors = colors;
exports.capitalized = capitalized;
exports.lowercased = lowercased;
exports.err = err;
exports.num = num;
/*  Not a pure module */
