// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newscore = 20;

var message = "hello world";

console.log("Enjoying the docs so far?");

console.log("hello");

console.log(1);

var A = {
  b: 4
};

var A$prime = {
  b: 4
};

var greeting = "hello!";

var score = 10;

var displayGreeting = true;

var result = 1;

exports.greeting = greeting;
exports.score = score;
exports.newscore = newscore;
exports.message = message;
exports.displayGreeting = displayGreeting;
exports.result = result;
exports.A = A;
exports.A$prime = A$prime;
/*  Not a pure module */
