// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var message = "Good morning!";

function displayMenu(param) {
  console.log("");
  
}

console.log("");

console.log("");

for(var x = 1; x <= 3; ++x){
  console.log(x);
  console.log(" ");
}

for(var x$1 = 3; x$1 >= 1; --x$1){
  console.log(x$1);
  console.log(" ");
}

var num = {
  contents: 0
};

while(Caml_obj.caml_lessthan(num, {
        contents: 3
      })) {
  console.log(num);
  num.contents = num.contents + 1 | 0;
};

var $$break = {
  contents: false
};

while(!$$break.contents) {
  if (Math.random() > 0.3) {
    $$break.contents = true;
  } else {
    console.log("Still running");
  }
};

var isMorning = true;

var showMenu = true;

exports.isMorning = isMorning;
exports.message = message;
exports.displayMenu = displayMenu;
exports.showMenu = showMenu;
exports.num = num;
exports.$$break = $$break;
/*  Not a pure module */
