// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log(10);

function displayMessage(m) {
  console.log(m._0);
  
}

displayMessage(/* Complete */{
      _0: "You did it!"
    });

var myArray = [
  1,
  2,
  3
];

if (myArray.length !== 3) {
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "patternMatching_destructuring.res",
          44,
          5
        ],
        Error: new Error()
      };
}

var item1 = myArray[0];

var item2 = myArray[1];

var data = {
  TAG: /* GoodResult */1,
  _0: "Product shipped!"
};

if (typeof data === "number") {
  console.log("Bah.");
} else if (data.TAG === /* BadResult */0) {
  console.log("Something's wrong. The error code is: " + "Product shipped!".toString());
} else {
  console.log("Success! Product shipped!");
}

var person1 = {
  TAG: /* Teacher */0,
  name: "Jane",
  age: 35
};

var message;

if (person1.TAG === /* Teacher */0) {
  var name = "Jane";
  switch (name) {
    case "Joe" :
    case "Mary" :
        message = "Hey, still going to the party on Saturday?";
        break;
    default:
      message = "Hello " + name + ".";
  }
} else {
  var name$1 = "Jane";
  var match = person1.reportCard;
  message = match.passing ? "Congrats " + name$1 + ", nice GPA of " + match.gpa.toString() : "Good luck next semester " + name$1 + "!";
}

var categoryId = 1;

var myStatus = {
  TAG: /* Vacations */0,
  _0: 10
};

if (typeof myStatus === "number") {
  console.log("Hey! How are you?");
} else {
  console.log("Come back in " + (10).toString() + " days!");
}

var coordinates = [
  10,
  20,
  30
];

var x = 10;

var student1 = {
  name: "John",
  age: 10
};

var name$2 = "John";

var myResult = /* Success */{
  _0: "You did it!"
};

var n = "John";

var isBig = true;

var myAnimal = /* Dog */0;

exports.coordinates = coordinates;
exports.x = x;
exports.student1 = student1;
exports.name = name$2;
exports.myResult = myResult;
exports.displayMessage = displayMessage;
exports.n = n;
exports.myArray = myArray;
exports.item1 = item1;
exports.item2 = item2;
exports.data = data;
exports.person1 = person1;
exports.message = message;
exports.isBig = isBig;
exports.myAnimal = myAnimal;
exports.categoryId = categoryId;
exports.myStatus = myStatus;
/*  Not a pure module */
